INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (101, 'Anurag Mundra', 'C-313,HOR-MEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (102, 'Prashant Pandey', 'B-313,HOR MEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (103, 'Harleen Kaur', 'J-306,HOR-WOMEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (104, 'Kushagra Jain', 'B-309,HOR-MEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (105, 'Yash Luhadiya', 'B-313,HOR-MEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (106, 'Aakrati Varma', 'J-306,HOR-WOMEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (107, 'Pratik Jain', 'C-313,HOR-MEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (108, 'Janki Mehta', 'J-301,HOR-WOMEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (109, 'Ankita Doshi', 'J-301,HOR-WOMEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (110, 'Bharat Singh', 'B-309,HOR-MEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (111, 'Swena Gupta', 'J-203,HOR-WOMEN,DAIICT', 'Gandhinagar', 'Gujarat', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (112, 'Paresh Kapoor', '10,Bhimnath Society,Vastrapur', 'Ahemdabad', 'Gujarat', 360375);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (113, 'Harshita Asawa', '23,Alankar Society,Behind Circuit House', 'Ahemdabad', 'Gujarat', 360375);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (114, 'Rahul Sharma', '25,Krishna Nagar', 'Bharatpur', 'Rajasthan', 387123);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (115, 'Kalpesh Chawla', '30,Sai Appartments,Shanti Nagar', 'SriGanganagar', 'Rajasthan', 382715);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (116, 'Ajay Ranawat', '45,Mithai Gali', 'Bhilwara', 'Rajasthan', 314337);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (117, 'Vijay Singh', '34,Aradhana Appartments,Indira Nagar', 'Jaipur', 'Rajasthan', 335997);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (118, 'Kunal Kapoor', '19,Sunar Mohalla', 'Dhar', 'Madhya Pradesh', 312347);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (119, 'Sunil Joshi', '20,Near NAHTA Coaching Center', 'Indore', 'Madhya Pradesh', 378657);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (120, 'Bhagwan Singh', '87,Hajratganj', 'Lucknow', 'Uttar Pradesh', 356457);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (121, 'Shawn Michaels', '25,Downway Street', 'New York City', 'New York', 10021);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (122, 'John Mclaen', '16,Kingstreet', 'New York City', 'New York', 10021);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (123, 'Sarita Verma', '203,Near Sukhadiya Circle', 'Udaipur', 'Rajasthan', 312007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (124, 'Karishma Kotak', '13,Near Sawai Maan Singh Stadium', 'Jodhpur', 'Gujarat', 342005);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (125, 'Sameer Soni', '15,Connaught Place', 'New Delhi', 'Delhi', 398507);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (126, 'Abhishek Porwal', '63,Shivraman Road', 'Bhubaneswar', 'Orissa', 362547);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (127, 'Aakash Patni', '16,Khau Gali', 'Mumbai', 'Maharashtra', 332447);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (128, 'Bheru Lal', '12,Luhar Mohalla', 'Bikaner', 'Rajasthan', 389657);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (129, 'N. Reddy', '34,Near Paradise Hotel', 'Hyderabad', 'Andhra Pradesh ', 386358);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (130, 'Kavita Joshi', '90,Nehru Nagar', 'Jamnagar', 'Gujarat', 352086);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (131, 'Sanjay Sodani', '78,Anthony Cross Road', 'Panaji', 'Goa', 387942);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (132, 'Sanjeev Tripathi', '25,Ashok Nagar', 'Kanpur', 'Uttar Pradesh', 333398);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (133, 'Vaibhav Doshi', '29,C.V.Raman Road', 'Thiruvananthpuram', 'Kerala', 345871);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (134, 'Geeta Sharma', '54,Rajnikant Road', 'Mysore', 'Karnataka', 363251);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (135, 'Anjali Singh', '29,Near Tejbahadur Valley', 'Dispur', 'Assam', 382558);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (136, 'Shayantani Ghosh', '36,Subhash Nagar', 'Kolkata', 'West Bengal', 396969);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (137, 'Laxman Shivraman', '80,Vivekanand Colony', 'Chennai', 'Tamil Nadu', 382007);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (138, 'Ankit Soni', '46,Teja Colony', 'Mayong', 'Sikkim', 387847);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (139, 'Naveen Kumar Salvi', 'R/23,Santoshi Nagar', 'Raipur', 'Chhattisgarh', 365407);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (140, 'Himanshu Jain', 'H/45,New Shimla', 'Shimla', 'Himachal Pradesh', 307010);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (141, 'Keshav Sodani', 'C/201,Shashtri Nagar', 'Indore', 'Madhya Pradesh', 378657);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (142, 'Lokesh Tripathi', 'D/125,Savita Apartments,Near Bhagat Singh Park', 'Amritsar', 'Punjab', 310207);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (143, 'Neeraj Sukhwal', 'J/306,Kamla Apartments,Gandhi Nagar', 'Kanpur', 'Uttar Pradesh', 333398);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (144, 'Niranjan Mundra', 'A/6,Bapu Nagar,Senthi', 'Chittorgarh', 'Rajasthan', 312001);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (145, 'Rahul Jain', '56,Near Kinston Hotel', 'Panaji', 'Goa', 387942);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (146, 'Subhash Singhal', 'D/106,Tejaji Chowk', 'Pune', 'Maharashtra', 371212);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (147, 'Lucky Sharma', '45,Ghatkopar', 'Mumbai', 'Maharashtra', 332447);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (148, 'Jeet Das', 'B/302,Anuradha Flats,Behind Police Line', 'Ludhiana', 'Punjab', 358210);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (149, 'V.R. Reddy', '36,Mangalagiri', 'Vijaywada', 'Andhra Pradesh', 311223);
INSERT INTO "Address" ("Address#", "Name", "Addr", "City", "State", "Pin_code") VALUES (150, 'Arpit Sarbhai', '45,Kishan Nagar', 'Bangalore', 'Karnataka', 365021);
